// Auto-generated by scripts/build-indexer-manifest.mjs — do not edit manually.
// Content hash of client/public/coding-agent/indexer/*.py + requirements.txt.
export const INDEXER_VERSION = 'b87726539ec7d2df';
